Repository prgrms-be-devcourse/NBE1_2_Team10, pull requests merged in 2024-09, with the labels that each got.

#17 `feat` : 리뷰 서비스 인터페이스를 만든다.
  application/src/main/java/core/application/reviews/exceptions/NoReviewCommentFoundException.java
  application/src/main/java/core/application/reviews/exceptions/NoReviewFoundException.java
  application/src/main/java/core/application/reviews/models/entities/ReviewCommentEntity.java
  application/src/main/java/core/application/reviews/models/entities/ReviewEntity.java
  application/src/main/java/core/application/reviews/services/ReviewCommentService.java
  application/src/main/java/core/application/reviews/services/ReviewCommentSortOrder.java
  application/src/main/java/core/application/reviews/services/ReviewService.java
  application/src/main/java/core/application/reviews/services/ReviewSortOrder.java
Labels: :zap: enhancement, 🔎 review

#18 Feat : 영화 서비스 인터페이스 정의
  application/src/main/java/core/application/movies/constant/Genre.java
  application/src/main/java/core/application/movies/constant/MovieSearch.java
  application/src/main/java/core/application/movies/models/dto/MainPageMovieRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MainPageMoviesRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MovieDetailRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MovieSimpleRespDTO.java
  application/src/main/java/core/application/movies/service/MovieService.java
Labels: :zap: enhancement, 🔎 review

#20 Feat : MyPage 관련 base code
  application/src/main/java/core/application/users/models/dto/DibCancelRespDTO.java
  application/src/main/java/core/application/users/models/dto/DibCreateReqDTO.java
  application/src/main/java/core/application/users/models/dto/DibDetailRespDTO.java
  application/src/main/java/core/application/users/models/dto/MyPageRespDTO.java
  application/src/main/java/core/application/users/models/entities/DibEntity.java
  application/src/main/java/core/application/users/models/entities/UserEntity.java
  application/src/main/java/core/application/users/service/MyPageService.java
Labels: :zap: enhancement, 🔎 review

#21 Feat : User 관련 base code
  application/src/main/java/core/application/users/models/dto/MessageResponseDTO.java
  application/src/main/java/core/application/users/models/dto/UserDTO.java
  application/src/main/java/core/application/users/service/UserService.java
Labels: :zap: enhancement, 🔎 review

#26 Feat : 마이페이지, 찜하기 관련 base code
  application/src/main/java/core/application/users/models/dto/DibCreateReqDTO.java
  application/src/main/java/core/application/users/models/dto/DibDetailRespDTO.java
  application/src/main/java/core/application/users/models/dto/DibRespDTO.java
  application/src/main/java/core/application/users/service/DibService.java
  application/src/main/java/core/application/users/service/MyPageService.java
Labels: 🔎 review

#28 Feat/#25/movie detail - KMDb base code
  application/build.gradle
  application/src/main/java/core/application/movies/Controller/MovieController.java
  application/src/main/java/core/application/movies/models/dto/MovieDetailRespDTO.java
  application/src/main/java/core/application/movies/service/MovieService.java
  application/src/main/java/core/application/movies/service/MovieServiceImpl.java
  application/src/main/resources/application.properties
Labels: 🔎 review

#31 Feat : cached_movie_table 컬럼 추가
  application/src/main/java/core/application/movies/models/entities/CachedMovieEntity.java
Labels: :no_entry_sign: invalid

#33 [Docs] - Merge `README.md` & `Issue template` to `develop`
  .github/ISSUE_TEMPLATE/⚡-기능-추가.md
  .github/ISSUE_TEMPLATE/⛏-리팩토링.md
  .github/ISSUE_TEMPLATE/✨-추후-계획.md
  .github/ISSUE_TEMPLATE/🐞-버그-제보.md
  .github/ISSUE_TEMPLATE/😥-도와주세요.md
  .github/ISSUE_TEMPLATE/🚫-수정-요청.md
  .github/ISSUE_TEMPLATE/🤔-궁금해요.md
  git convention/README.md
Labels: documentation

#32 Feat/#23/mybatis query - `ReviewCommentRepository` 관련 `MyBatis` 쿼리 추가
  application/build.gradle
  application/src/main/java/core/application/config/mybatis/MyBatisConfig.java
  application/src/main/java/core/application/config/mybatis/UUIDTypeHandler.java
  application/src/main/java/core/application/reviews/models/entities/ReviewCommentEntity.java
  application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewCommentRepository.java
  application/src/main/java/core/application/reviews/repositories/mybatis/ReviewCommentMapperProvider.java
  application/src/main/resources/application.properties
  application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
Labels: :zap: enhancement, 🔎 review

#16 #10 PR 리뷰 내용, [09/26] 토의 내용 반영한 베이스 코드 검토
  .gitignore
  application/.gitignore
  application/build.gradle
  application/gradle/wrapper/gradle-wrapper.jar
  application/gradle/wrapper/gradle-wrapper.properties
  application/gradlew
  application/gradlew.bat
  application/settings.gradle
  application/src/main/java/core/application/Application.java
  application/src/main/java/core/application/config/PrivateConfig.java
  application/src/main/java/core/application/config/mybatis/MyBatisConfig.java
  application/src/main/java/core/application/config/mybatis/UUIDTypeHandler.java
  application/src/main/java/core/application/movies/Controller/MovieController.java
  application/src/main/java/core/application/movies/constant/Genre.java
  application/src/main/java/core/application/movies/constant/MovieSearch.java
  application/src/main/java/core/application/movies/models/dto/MainPageMovieRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MainPageMoviesRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MovieDetailRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MovieSimpleRespDTO.java
  application/src/main/java/core/application/movies/models/entities/CachedMovieEntity.java
  application/src/main/java/core/application/movies/models/entities/CommentEntity.java
  application/src/main/java/core/application/movies/repositories/CachedMovieRepository.java
  application/src/main/java/core/application/movies/repositories/CommentRepository.java
  application/src/main/java/core/application/movies/service/MovieService.java
  application/src/main/java/core/application/movies/service/MovieServiceImpl.java
  application/src/main/java/core/application/reviews/exceptions/NoReviewCommentFoundException.java
  application/src/main/java/core/application/reviews/exceptions/NoReviewFoundException.java
  application/src/main/java/core/application/reviews/models/entities/ReviewCommentEntity.java
  application/src/main/java/core/application/reviews/models/entities/ReviewEntity.java
  application/src/main/java/core/application/reviews/repositories/ReviewCommentRepository.java
  application/src/main/java/core/application/reviews/repositories/ReviewRepository.java
  application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewCommentRepository.java
  application/src/main/java/core/application/reviews/repositories/mybatis/ReviewCommentMapperProvider.java
  application/src/main/java/core/application/reviews/services/ReviewCommentService.java
  application/src/main/java/core/application/reviews/services/ReviewCommentSortOrder.java
  application/src/main/java/core/application/reviews/services/ReviewService.java
  application/src/main/java/core/application/reviews/services/ReviewSortOrder.java
  application/src/main/java/core/application/users/models/dto/DibDetailRespDTO.java
  application/src/main/java/core/application/users/models/dto/DibRespDTO.java
  application/src/main/java/core/application/users/models/dto/MessageResponseDTO.java
  application/src/main/java/core/application/users/models/dto/MyPageRespDTO.java
  application/src/main/java/core/application/users/models/dto/UserDTO.java
  application/src/main/java/core/application/users/models/entities/DibEntity.java
  application/src/main/java/core/application/users/models/entities/UserEntity.java
  application/src/main/java/core/application/users/models/entities/UserRole.java
  application/src/main/java/core/application/users/repositories/DibRepository.java
  application/src/main/java/core/application/users/repositories/UserRepository.java
  application/src/main/java/core/application/users/service/DibService.java
  application/src/main/java/core/application/users/service/MyPageService.java
  application/src/main/java/core/application/users/service/UserService.java
  application/src/main/resources/application.properties
  application/src/test/java/core/application/ApplicationTests.java
  application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
  assets/DDL.sql
  assets/ERD.png
Labels: :zap: enhancement, 🔎 review

#39 Feat : CachedMovieRepository SQL 작성 및 구현
  application/src/main/java/core/application/movies/models/entities/CachedMovieEntity.java
  application/src/main/java/core/application/movies/repositories/CachedMovieRepositoryImpl.java
  application/src/main/java/core/application/movies/repositories/mapper/CachedMovieMapper.java
  application/src/main/resources/application.properties
  application/src/main/resources/mappers/movies/CacheMovieMapper.xml
  application/src/test/java/core/application/movies/MovieRepositoryTest.java
Labels: :zap: enhancement
