Repository prgrms-be-devcourse/NBE1_2_Team10, pull requests merged in 2024-10, with the labels that each got.

#45 Feat : 메인페이지 영화 목록 조회
  application/src/main/java/core/application/config/WebClientConfig.java
  application/src/main/java/core/application/movies/controller/MovieController.java
  application/src/main/java/core/application/movies/models/dto/MainPageMovieRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MainPageMoviesRespDTO.java
  application/src/main/java/core/application/movies/repositories/CachedMovieRepository.java
  application/src/main/java/core/application/movies/repositories/CachedMovieRepositoryImpl.java
  application/src/main/java/core/application/movies/repositories/mapper/CachedMovieMapper.java
  application/src/main/java/core/application/movies/service/MovieService.java
  application/src/main/java/core/application/movies/service/MovieServiceImpl.java
  application/src/main/resources/mappers/movies/CacheMovieMapper.xml
  application/src/test/java/core/application/movies/repository/MovieRepositoryTest.java
  application/src/test/java/core/application/movies/service/MovieServiceTest.java
Labels: :zap: enhancement

#47 Feat/#38 - `ReviewCommentService` 구현체 추가
  application/src/main/java/core/application/reviews/repositories/ReviewCommentRepository.java
  application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewCommentRepository.java
  application/src/main/java/core/application/reviews/repositories/mybatis/ReviewCommentMapperProvider.java
  application/src/main/java/core/application/reviews/services/ReviewCommentService.java
  application/src/main/java/core/application/reviews/services/ReviewCommentServiceImpl.java
  application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
  application/src/test/java/core/application/reviews/services/ReviewCommentServiceImplTest.java
Labels: :zap: enhancement

#61 Feat : 찜 테스트 코드 작성
  application/src/main/java/core/application/users/mapper/DibMapper.java
  application/src/main/java/core/application/users/models/dto/DibRespDTO.java
  application/src/main/java/core/application/users/repositories/DibRepository.java
  application/src/main/java/core/application/users/repositories/DibRepositoryImpl.java
  application/src/main/java/core/application/users/service/DibService.java
  application/src/main/java/core/application/users/service/DibServiceImpl.java
  application/src/main/resources/mappers/users/DibMapper.xml
  application/src/test/java/core/application/users/repositories/DibRepositoryImplTest.java
  application/src/test/java/core/application/users/service/DibServiceImplTest.java
Labels: :zap: enhancement

#59 `Feat/#54/` - `후기 포스팅 댓글` 컨트롤러 구현
  application/src/main/java/core/application/reviews/ReviewExceptionHandler.java
  application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
  application/src/main/java/core/application/reviews/exceptions/InvalidCommentContentException.java
  application/src/main/java/core/application/reviews/exceptions/NotCommentOwnerException.java
  application/src/main/java/core/application/reviews/models/dto/request/CommonCommentReqDTO.java
  application/src/main/java/core/application/reviews/models/dto/request/CreateCommentReqDTO.java
  application/src/main/java/core/application/reviews/models/dto/request/EditCommentReqDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/CommonCommentRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/CreateCommentRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/EditCommentRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/MessageRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/ShowCommentsRespDTO.java
  application/src/main/java/core/application/reviews/repositories/ReviewCommentRepository.java
  application/src/main/java/core/application/reviews/repositories/mapper/ReviewMapper.java
  application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewCommentRepository.java
  application/src/main/java/core/application/reviews/services/ReviewCommentService.java
  application/src/main/java/core/application/reviews/services/ReviewCommentServiceImpl.java
  application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
  application/src/test/java/core/application/reviews/services/ReviewCommentServiceImplTest.java
Labels: :zap: enhancement, 🔎 review

#56 Feat : CommentRepository 구현
  application/src/main/java/core/application/movies/repositories/CommentRepositoryImpl.java
  application/src/main/java/core/application/movies/repositories/mapper/CommentMapper.java
  application/src/main/resources/mappers/movies/CommentMapper.xml
  application/src/test/java/core/application/movies/repository/CommentRepositoryTest.java
Labels: :zap: enhancement

#65 Feat : 마이페이지 서비스
  application/src/main/java/core/application/users/mapper/DibMapper.java
  application/src/main/java/core/application/users/mapper/UserMapper.java
  application/src/main/java/core/application/users/models/dto/DibDetailRespDTO.java
  application/src/main/java/core/application/users/models/dto/MyPageRespDTO.java
  application/src/main/java/core/application/users/repositories/DibRepository.java
  application/src/main/java/core/application/users/repositories/DibRepositoryImpl.java
  application/src/main/java/core/application/users/repositories/UserRepository.java
  application/src/main/java/core/application/users/repositories/UserRepositoryImpl.java
  application/src/main/java/core/application/users/service/MyPageService.java
  application/src/main/java/core/application/users/service/MyPageServiceImpl.java
  application/src/main/resources/mappers/users/DibMapper.xml
  application/src/main/resources/mappers/users/UserMapper.xml
  application/src/test/java/core/application/users/repositories/UserRepositoryImplTest.java
  application/src/test/java/core/application/users/service/MyPageServiceImplTest.java
Labels: :zap: enhancement

#66 Feat : 영화 검색 및 카테고리 기능 구현
  application/src/main/java/core/application/movies/constant/Genre.java
  application/src/main/java/core/application/movies/constant/MovieSearch.java
  application/src/main/java/core/application/movies/controller/MovieController.java
  application/src/main/java/core/application/movies/controller/MovieExceptionAdvice.java
  application/src/main/java/core/application/movies/exception/NoMovieException.java
  application/src/main/java/core/application/movies/exception/WrongAccessException.java
  application/src/main/java/core/application/movies/models/dto/MovieSearchRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MovieSimpleRespDTO.java
  application/src/main/java/core/application/movies/repositories/CachedMovieRepository.java
  application/src/main/java/core/application/movies/repositories/CachedMovieRepositoryImpl.java
  application/src/main/java/core/application/movies/repositories/mapper/CachedMovieMapper.java
  application/src/main/java/core/application/movies/service/MovieService.java
  application/src/main/java/core/application/movies/service/MovieServiceImpl.java
  application/src/main/resources/mappers/movies/CacheMovieMapper.xml
  application/src/test/java/core/application/movies/contoller/MovieContollerTest.java
Labels: :question: question, :zap: enhancement

#79 Hotfix : `MovieServiceImpl` 삭제된 필드 추가
  application/src/main/java/core/application/movies/service/MovieServiceImpl.java
  application/src/main/resources/application.properties
Labels: :lady_beetle: bug

#85 [Fix] : MybatisConfig 등록 설정 복구
  application/src/main/resources/application.properties
Labels: :lady_beetle: bug

#86 [Docs] `movies`, `reviews` Swagger 적용
  application/build.gradle
  application/src/main/java/core/application/config/SwaggerConfig.java
  application/src/main/java/core/application/movies/controller/CommentController.java
  application/src/main/java/core/application/movies/controller/MovieController.java
  application/src/main/java/core/application/movies/models/dto/CommentRespDTO.java
  application/src/main/java/core/application/movies/models/dto/CommentWriteReqDTO.java
  application/src/main/java/core/application/movies/models/dto/MainPageMovieRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MainPageMoviesRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MovieDetailRespDTO.java
  application/src/main/java/core/application/movies/models/dto/MovieSearchRespDTO.java
  application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
  application/src/main/java/core/application/reviews/models/dto/request/CommonCommentReqDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/ShowCommentsRespDTO.java
  application/src/main/java/core/application/reviews/models/entities/ReviewCommentEntity.java
  application/src/main/resources/application.properties
Labels: documentation

#64 Feat : 회원 관리 구현
  application/build.gradle
  application/src/main/java/core/application/config/RedisConfig.java
  application/src/main/java/core/application/config/SecurityConfig.java
  application/src/main/java/core/application/filter/CustomLoginFilter.java
  application/src/main/java/core/application/filter/CustomLogoutFilter.java
  application/src/main/java/core/application/filter/JWTFilter.java
  application/src/main/java/core/application/security/AuthenticatedUserService.java
  application/src/main/java/core/application/security/CustomUserDetails.java
  application/src/main/java/core/application/security/CustomUserDetailsService.java
  application/src/main/java/core/application/security/JwtTokenUtil.java
  application/src/main/java/core/application/security/RedisService.java
  application/src/main/java/core/application/security/RedisServiceImpl.java
  application/src/main/java/core/application/security/TokenService.java
  application/src/main/java/core/application/users/controller/UserController.java
  application/src/main/java/core/application/users/mapper/UserMapper.java
  application/src/main/java/core/application/users/models/dto/MessageResponseDTO.java
  application/src/main/java/core/application/users/models/dto/UserDTO.java
  application/src/main/java/core/application/users/repositories/UserRepository.java
  application/src/main/java/core/application/users/repositories/UserRepositoryImpl.java
  application/src/main/java/core/application/users/service/UserService.java
  application/src/main/java/core/application/users/service/UserServiceImpl.java
  application/src/main/resources/application.properties
  application/src/main/resources/mappers/users/UserMapper.xml
  application/src/test/java/core/application/users/repositories/UserRepositoryImplTest.java
Labels: :zap: enhancement

#88 Feat : 마이페이지 찜 controller 구현
  application/src/main/java/core/application/users/controller/DibController.java
  application/src/main/java/core/application/users/controller/MyPageController.java
  application/src/main/resources/mappers/users/DibMapper.xml
Labels: :zap: enhancement

#93 [Refactor] `movie` 도메인 리팩토링
  application/src/main/java/core/application/api/response/ApiResponse.java
  application/src/main/java/core/application/api/response/code/Message.java
  application/src/main/java/core/application/api/response/code/status/ErrorStatus.java
  application/src/main/java/core/application/api/response/code/status/SuccessStatus.java
  application/src/main/java/core/application/movies/constant/KmdbParameter.java
  application/src/main/java/core/application/movies/constant/MovieSearch.java
  application/src/main/java/core/application/movies/controller/CommentController.java
  application/src/main/java/core/application/movies/controller/GlobalExceptionHandler.java
  application/src/main/java/core/application/movies/controller/MovieController.java
  application/src/main/java/core/application/movies/controller/MovieExceptionAdvice.java
  application/src/main/java/core/application/movies/exception/InvalidWriteCommentException.java
  application/src/main/java/core/application/movies/exception/MovieExceptionHandler.java
  application/src/main/java/core/application/movies/exception/NoSearchResultException.java
  application/src/main/java/core/application/movies/exception/NotCommentWriterException.java
  application/src/main/java/core/application/movies/exception/NotFoundUrlException.java
  application/src/main/java/core/application/movies/exception/WrongAccessException.java
  application/src/main/java/core/application/movies/exception/WrongWriteCommentException.java
  application/src/main/java/core/application/movies/models/dto/CommentReactionRespDTO.java
  application/src/main/java/core/application/movies/models/dto/request/CommentWriteReqDTO.java
  application/src/main/java/core/application/movies/models/dto/response/CommentReactionRespDTO.java
  application/src/main/java/core/application/movies/models/dto/response/CommentRespDTO.java
  application/src/main/java/core/application/movies/models/dto/response/MainPageMovieRespDTO.java
  application/src/main/java/core/application/movies/models/dto/response/MainPageMoviesRespDTO.java
  application/src/main/java/core/application/movies/models/dto/response/MovieDetailRespDTO.java
  application/src/main/java/core/application/movies/models/dto/response/MovieSearchRespDTO.java
  application/src/main/java/core/application/movies/models/entities/CommentEntity.java
  application/src/main/java/core/application/movies/repositories/comment/CommentDislikeRepository.java
  application/src/main/java/core/application/movies/repositories/comment/CommentLikeRepository.java
  application/src/main/java/core/application/movies/repositories/comment/CommentRepository.java
  application/src/main/java/core/application/movies/repositories/comment/CommentRepositoryImpl.java
  application/src/main/java/core/application/movies/repositories/mapper/CommentMapper.java
  application/src/main/java/core/application/movies/repositories/movie/CachedMovieRepository.java
  application/src/main/java/core/application/movies/repositories/movie/CachedMovieRepositoryImpl.java
  application/src/main/java/core/application/movies/repositories/movie/KmdbApiRepository.java
  application/src/main/java/core/application/movies/service/CommentService.java
  application/src/main/java/core/application/movies/service/MovieService.java
  application/src/main/java/core/application/movies/service/MovieServiceImpl.java
  application/src/main/java/core/application/users/service/DibServiceImpl.java
  application/src/main/java/core/application/users/service/MyPageServiceImpl.java
  application/src/main/resources/mappers/movies/CommentMapper.xml
  application/src/test/java/core/application/movies/contoller/MovieContollerTest.java
  application/src/test/java/core/application/movies/repository/CommentRepositoryTest.java
  application/src/test/java/core/application/movies/repository/MovieRepositoryTest.java
  application/src/test/java/core/application/movies/service/CommentServiceTest.java
  application/src/test/java/core/application/movies/service/MovieServiceTest.java
  application/src/test/java/core/application/users/service/DibServiceImplTest.java
  application/src/test/java/core/application/users/service/MyPageServiceImplTest.java
Labels: :star2: Refactoring

#97 [Refactor] `review` 도메인 리팩토링
  application/src/main/java/core/application/api/response/code/status/ErrorStatus.java
  application/src/main/java/core/application/reviews/ReviewExceptionHandler.java
  application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
  application/src/main/java/core/application/reviews/exceptions/InvalidPageException.java
  application/src/main/java/core/application/reviews/exceptions/ReviewExceptionHandler.java
  application/src/main/java/core/application/reviews/models/entities/ReviewCommentEntity.java
  application/src/main/java/core/application/reviews/models/entities/ReviewEntity.java
  application/src/main/java/core/application/reviews/services/ReviewCommentService.java
  application/src/main/java/core/application/reviews/services/ReviewCommentServiceImpl.java
Labels: :star2: Refactoring

#91 `Feat/#87` - 클라우드 이미지 업로드 기능 추가
  application/build.gradle
  application/src/main/java/core/application/reviews/controllers/ImageUploadController.java
  application/src/main/java/core/application/reviews/exceptions/FailedToUploadImageException.java
  application/src/main/java/core/application/reviews/exceptions/NoImageWereGivenExcpetion.java
  application/src/main/java/core/application/reviews/services/images/GCSImageUploadService.java
  application/src/main/java/core/application/reviews/services/images/ImageUploadService.java
  application/src/main/resources/application.properties
  application/src/test/java/core/application/reviews/services/images/ImageUploadServiceTest.java
Labels: :zap: enhancement, 🔎 review

#98 [Docs] `user` 도메인 Swagger 적용
  application/src/main/java/core/application/config/SecurityConfig.java
  application/src/main/java/core/application/users/controller/DibController.java
  application/src/main/java/core/application/users/controller/MyPageController.java
  application/src/main/java/core/application/users/controller/UserController.java
Labels: documentation

#100 [Docs] CkEditor Swagger 적용
  application/src/main/java/core/application/reviews/controllers/ImageUploadController.java
Labels: documentation

#102 `Feat/#92` - `Review` 관련 기능 구현 완료
  application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
  application/src/main/java/core/application/reviews/controllers/ReviewController.java
  application/src/main/java/core/application/reviews/exceptions/InvalidReviewEditException.java
  application/src/main/java/core/application/reviews/exceptions/InvalidReviewWriteException.java
  application/src/main/java/core/application/reviews/exceptions/NotReviewOwnerException.java
  application/src/main/java/core/application/reviews/models/dto/request/reviews/CreateReviewReqDTO.java
  application/src/main/java/core/application/reviews/models/dto/request/reviews/EditReviewReqDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/reviews/AdjustLikeRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/reviews/ListReviewsRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/reviews/ReviewInfoRespDTO.java
  application/src/main/java/core/application/reviews/models/entities/ReviewEntity.java
  application/src/main/java/core/application/reviews/repositories/ReviewRepository.java
  application/src/main/java/core/application/reviews/repositories/ReviewRepositoryImpl.java
  application/src/main/java/core/application/reviews/repositories/mapper/ReviewMapper.java
  application/src/main/java/core/application/reviews/services/ReviewService.java
  application/src/main/java/core/application/reviews/services/ReviewServiceImpl.java
  application/src/main/resources/mappers/review/ReviewMapper.xml
  application/src/test/java/core/application/reviews/repositories/ReviewRepositoryTest.java
  application/src/test/java/core/application/reviews/services/ReviewServiceImplTest.java
Labels: :zap: enhancement, 🔎 review

#101 [Refactor] JWT 코드 추가에 따른 `movie` 리팩토링
  application/src/main/java/core/application/api/exception/CommonForbiddenException.java
  application/src/main/java/core/application/api/exception/GlobalExceptionHandler.java
  application/src/main/java/core/application/api/response/code/status/ErrorStatus.java
  application/src/main/java/core/application/config/SecurityConfig.java
  application/src/main/java/core/application/config/WebClientConfig.java
  application/src/main/java/core/application/filter/JWTFilter.java
  application/src/main/java/core/application/movies/controller/CommentController.java
  application/src/main/java/core/application/movies/exception/MovieExceptionHandler.java
  application/src/main/java/core/application/movies/service/CommentService.java
  application/src/main/java/core/application/security/JwtAuthenticationEntryPoint.java
Labels: :star2: Refactoring

#111 [Hotfix] `NotMatchMovieCommentException` 추가
  application/src/main/java/core/application/movies/exception/NotMatchMovieCommentException.java
Labels: :lady_beetle: bug

#109 [Refactor] Review Controller `ApiResponse` 및 `Swagger` 적용
  application/src/main/java/core/application/reviews/controllers/ReviewController.java
Labels: :star2: Refactoring

#122 Refactor : 마이페이지, 찜 리팩토링
  application/src/main/java/core/application/users/controller/DibController.java
  application/src/main/java/core/application/users/controller/MyPageController.java
  application/src/main/java/core/application/users/service/DibService.java
  application/src/main/java/core/application/users/service/DibServiceImpl.java
  application/src/main/resources/mappers/users/UserMapper.xml
Labels: :star2: Refactoring

#120 Hotfix/#199 - `Review`, `Review Comment` 관련 버그 수정
  application/src/main/java/core/application/config/SecurityConfig.java
  application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
  application/src/main/java/core/application/reviews/controllers/ReviewController.java
  assets/DDL.sql
Labels: :lady_beetle: bug, :star2: Refactoring

#117 [Hotfix] 로그인/회원가입/JWT 만료 오류 수정
  application/src/main/java/core/application/api/exception/GlobalExceptionHandler.java
  application/src/main/java/core/application/api/exception/InvalidLoginException.java
  application/src/main/java/core/application/api/response/code/status/ErrorStatus.java
  application/src/main/java/core/application/filter/CustomLoginFilter.java
  application/src/main/java/core/application/filter/JWTFilter.java
  application/src/main/java/core/application/security/CustomUserDetails.java
  application/src/main/java/core/application/users/exception/DuplicateEmailException.java
  application/src/main/java/core/application/users/exception/UserExceptionHandler.java
  application/src/main/java/core/application/users/models/dto/UserDTO.java
  application/src/main/java/core/application/users/repositories/UserRepository.java
  application/src/main/java/core/application/users/repositories/UserRepositoryImpl.java
  application/src/main/java/core/application/users/service/UserServiceImpl.java
Labels: :lady_beetle: bug, :star2: Refactoring

#140 `Refactor/#138` - `Review` 관련 `Repository` 들 `MyBatis` 프로필로 분리 완료
  application/src/main/java/core/application/config/mybatis/MyBatisConfig.java
  application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewCommentRepository.java
  application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewRepository.java
  application/src/main/java/core/application/reviews/repositories/mybatis/ReviewCommentMapperProvider.java
  application/src/main/java/core/application/reviews/repositories/mybatis/ReviewMapperProvider.java
  application/src/main/java/core/application/reviews/repositories/mybatis/mappers/ReviewCommentMapper.java
  application/src/main/java/core/application/reviews/repositories/mybatis/mappers/ReviewMapper.java
  application/src/main/resources/mappers/review/ReviewCommentMapper.xml
  application/src/main/resources/mappers/review/ReviewMapper.xml
  application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
  application/src/test/java/core/application/reviews/repositories/ReviewRepositoryTest.java
  assets/DDL.sql
Labels: :star2: Refactoring, 🔎 review

#144 [Refactor] 한줄평 기능 JPA 마이그레이션
  application/build.gradle
  application/src/main/java/core/application/movies/controller/CommentController.java
  application/src/main/java/core/application/movies/models/entities/CachedMovieEntity.java
  application/src/main/java/core/application/movies/models/entities/CommentDislike.java
  application/src/main/java/core/application/movies/models/entities/CommentEntity.java
  application/src/main/java/core/application/movies/models/entities/CommentLike.java
  application/src/main/java/core/application/movies/repositories/comment/CommentDislikeRepository.java
  application/src/main/java/core/application/movies/repositories/comment/CommentLikeRepository.java
  application/src/main/java/core/application/movies/repositories/comment/CommentRepository.java
  application/src/main/java/core/application/movies/repositories/comment/CommentRepositoryImpl.java
  application/src/main/java/core/application/movies/repositories/comment/jpa/CommentDislikeRepositoryJPAImpl.java
  application/src/main/java/core/application/movies/repositories/comment/jpa/CommentLikeRepositoryJPAImpl.java
  application/src/main/java/core/application/movies/repositories/comment/jpa/CommentRepositoryJPAImpl.java
  application/src/main/java/core/application/movies/repositories/comment/jpa/JpaCommentDislikeRepository.java
  application/src/main/java/core/application/movies/repositories/comment/jpa/JpaCommentLikeRepository.java
  application/src/main/java/core/application/movies/repositories/comment/jpa/JpaCommentRepository.java
  application/src/main/java/core/application/movies/repositories/comment/mybatis/MybatisCommentDislikeRepository.java
  application/src/main/java/core/application/movies/repositories/comment/mybatis/MybatisCommentLikeRepository.java
  application/src/main/java/core/application/movies/repositories/comment/mybatis/MybatisCommentRepository.java
  application/src/main/java/core/application/movies/repositories/mapper/CommentMapper.java
  application/src/main/java/core/application/movies/service/CommentService.java
  application/src/main/resources/mappers/movies/CommentMapper.xml
  application/src/test/java/core/application/movies/repository/CommentRepositoryTest.java
  application/src/test/java/core/application/movies/repository/MovieRepositoryTest.java
  application/src/test/java/core/application/movies/service/CommentServiceTest.java
Labels: :star2: Refactoring, :zap: enhancement

#148 Refactor/#147 - `Review` 관련 응답 형태 `Page` 로 변경
  application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
  application/src/main/java/core/application/reviews/controllers/ReviewController.java
  application/src/main/java/core/application/reviews/repositories/ReviewRepository.java
  application/src/main/java/core/application/reviews/repositories/mybatis/MyBatisReviewRepository.java
  application/src/main/java/core/application/reviews/repositories/mybatis/mappers/ReviewMapper.java
  application/src/main/java/core/application/reviews/services/ReviewService.java
  application/src/main/java/core/application/reviews/services/ReviewServiceImpl.java
  application/src/main/resources/mappers/review/ReviewCommentMapper.xml
  application/src/main/resources/mappers/review/ReviewMapper.xml
  application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
  application/src/test/java/core/application/reviews/repositories/ReviewRepositoryTest.java
Labels: :star2: Refactoring

#149 Feat/#141 - `Review` 관련 `JPA` 마이그레이션 완료
  application/build.gradle
  application/src/main/java/core/application/reviews/controllers/ReviewCommentController.java
  application/src/main/java/core/application/reviews/controllers/ReviewController.java
  application/src/main/java/core/application/reviews/models/dto/response/ShowCommentsRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/comments/CommonCommentRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/comments/CreateCommentRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/comments/EditCommentRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/comments/ShowCommentsRespDTO.java
  application/src/main/java/core/application/reviews/models/dto/response/reviews/ListReviewsRespDTO.java
  application/src/main/java/core/application/reviews/models/entities/ReviewCommentEntity.java
  application/src/main/java/core/application/reviews/models/entities/ReviewEntity.java
  application/src/main/java/core/application/reviews/repositories/ReviewCommentRepository.java
  application/src/main/java/core/application/reviews/repositories/jpa/ReviewCommentRepositoryJpaImpl.java
  application/src/main/java/core/application/reviews/repositories/jpa/ReviewRepositoryJpaImpl.java
  application/src/main/java/core/application/reviews/repositories/jpa/repositories/JpaReviewCommentRepository.java
  application/src/main/java/core/application/reviews/repositories/jpa/repositories/JpaReviewRepository.java
  application/src/main/resources/application.properties
  application/src/test/java/core/application/reviews/repositories/ReviewCommentRepositoryTest.java
  application/src/test/java/core/application/reviews/services/ReviewCommentServiceImplTest.java
  application/src/test/java/core/application/reviews/services/ReviewServiceImplTest.java
  assets/DDL.sql
Labels: :zap: enhancement

#145 [Refactor] `CacheMovieEntity` JPA 마이그레이션
  application/src/main/java/core/application/movies/controller/MovieController.java
  application/src/main/java/core/application/movies/repositories/mapper/CachedMovieMapper.java
  application/src/main/java/core/application/movies/repositories/movie/CachedMovieRepository.java
  application/src/main/java/core/application/movies/repositories/movie/jpa/CachedMovieRepositoryJPAImpl.java
  application/src/main/java/core/application/movies/repositories/movie/jpa/JpaCachedMovieRepository.java
  application/src/main/java/core/application/movies/repositories/movie/mybatis/MybatisCachedMovieRepository.java
  application/src/main/java/core/application/movies/service/MovieService.java
  application/src/main/java/core/application/movies/service/MovieServiceImpl.java
  application/src/main/resources/mappers/movies/CacheMovieMapper.xml
  application/src/test/java/core/application/movies/repository/MovieRepositoryTest.java
Labels: :star2: Refactoring, :zap: enhancement

#156 Refactor/#153 - `DibRepository` `MyBatis` 분리 & 테스트 코드 개선
  application/src/main/java/core/application/users/models/entities/DibEntity.java
  application/src/main/java/core/application/users/models/entities/UserEntity.java
  application/src/main/java/core/application/users/repositories/DibRepository.java
  application/src/main/java/core/application/users/repositories/mybatis/MyBatisDibRepository.java
  application/src/test/java/core/application/users/repositories/DibRepositoryImplTest.java
  application/src/test/java/core/application/users/repositories/DibRepositoryTest.java
  application/src/test/java/core/application/users/repositories/UserRepositoryTest.java
  application/src/test/java/core/application/users/service/MyPageServiceImplTest.java
Labels: :star2: Refactoring, 🔎 review

#155 [Refactor] 한줄평 조회 및 작성 `alias` 리팩토링
  application/src/main/java/core/application/movies/controller/CommentController.java
  application/src/main/java/core/application/movies/models/dto/response/CommentRespDTO.java
  application/src/main/java/core/application/movies/repositories/comment/jpa/JpaCommentRepository.java
  application/src/main/java/core/application/movies/service/CommentService.java
  application/src/main/java/core/application/security/service/TokenService.java
  application/src/main/java/core/application/users/models/entities/UserEntity.java
  application/src/main/resources/mappers/movies/CommentMapper.xml
  application/src/test/java/core/application/movies/service/CommentServiceTest.java
Labels: :star2: Refactoring

#165 [Bugfix] filter 경로 문제
  application/src/main/java/core/application/filter/JWTFilter.java
Labels: :lady_beetle: bug
